var words7 = [
"window",
"normal train",
"queue, line",
"peculiarity; uniqueness; characteristic",
"history",
"academic background",
"history of japan",
"playing (noun)",
"bowl; vessel; container",
"musical instrument",
"to reach; to arrive; to get through; to get at",
"out of one's reach",
"general; universal、ordinary; average;",
"box; case; chest;",
"form; shape; figure",
"variety; kind; type; category",
"ingredients; material",
"right side; right hand",
"the inland side of japan",
"green",
"yellow; amber",
"to throw away; to cast away; to dump; to discard",
"to increase; to multiply",
"to increase; to grow",
"to fly; to soar",
"aeroplane; airplane; aircraft",
"airport",
"fast; quick; hasty; brisk",
"high speed; high gear"
];
