var words = [
"An old Story opening",
"An old story",
"Bamboo",
"To shine/to glow",
"to bring back/ to come back with",
"to raise",
"education",
"wife",
"to request",
"enthusiastic",
"hot to the touch",
"to reject",
"to convey, to report, to communicate",
"neck",
"sad",
"to cry",
"a worry",
"to go meet someone",
"to accept, approve, permit",
"to protect, to guard",
"to surround, encircle",
"state; state of affairs; situation; circumstances",
"various",
"to leave behind",
"too bad, unfortunate"
];
