var words6 = [
"To love",
"To die",
"death, mortality",
"poetry collection",
"abundant, plentiful",
"to recognize; to recognise; to observe; to notice",
"poor; needy",
"to suffer; to groan",
"bitter",
"(religious) faith; belief;",
"to believe;",
"agriculture",
"agricultural community; farm village",
"to be useful; to be helpful; to serve the purpose",
"passion; enthusiasm; zeal",
"love; affection",
"(cultural) exchange; interchange; interaction; (inter-) mingling;",
"to stream; to flow ",
"happiness; good fortune;",
"to want; to wish for",
"individual; private person; personal;",
"sentence; article; composition",
"to get; to earn; to acquire;",
"triumph; prosperity",
"to be facing",
"the earth; the globe",
"universe; cosmos; space",
"quiet; silent",
"to laugh",
"to get tired; to tire"
];
