var words = [
"study abroad",
"classroom",
"professor, teacher",
"to lose; to part with",
"rudeness, to be rude",
"failure",
"to lose, to be beaten, to be unsuccessful",
"for the first time",
"beginning, first",
"together",
"face",
"question",
"to be hit, to strike, to be equivalent to",
"truth, reality",
"female, female gender",
"male, male gender",
"sex/gender",
"extremely",
"interest (in something)",
"experience",
"to be surprised",
"violent, rude",
"understanding, comprehension",
"parents",
"both",
"fellow, comrade",
"to examine, to research/investigate",
"tune, tone, mood, condition",
"subject, contents, matter, substance",
];
